apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - solar.mahiy.local
    secretName: myapp-tls
  rules:
  - host: solar.mahity.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: solar-service
            port:
              number: 80